title: PLAZA

exclude:
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
