title: PLAZA

exclude:
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
